#!/usr/bin/env bash
# Configures Nginx to add X-Served-By header with the server's hostname
set -e
apt-get update
apt-get install -y nginx
hostname=$(hostname)
echo "\n    add_header X-Served-By $hostname;" >> /etc/nginx/sites-available/default
service nginx restart
